### ISSUE TITLE
cmd update dpg-copyright: and/or output from licensecheck causes error.

### ISSUE THREAD

**Issue by rerdavies** [dod38fr/config-model#27] opened 2021-08-24 17:58 UTC
Offending value: 'Please fill license CC-BY-SA-4.0 and/or ISC from header of react/node_modules/glob/*'
Error: Data extracted from source file is corrupted:
Configuration item 'Files:"react/node_modules/glob/*" License short_name' has a wrong value:
	value 'CC-BY-SA-4.0 and/or ISC' does not match grammar from model

Particularly paitful because it takes about 15 minutes to run. So I have to override the license, and wait 15 minutes to get the next error caused by a dual-licensed package.

**Comment by dod38fr** [comment] 2021-09-07 17:55
Right... This "and/or" output from licensecheck is troublesome although I understand why licensecheck cannot decide whether a "or" or a "and" should be used.

This problem is made worse because licensecheck takes a lot of time to parse files. I guess a cache would really improve this problem (A cache using a md5 key of the file content could be quite useful)

What I can do:
* allow "and/or" and issue a warning when this value is returned by license
* add a cache for licensecheck results.

What do you think ?

**Comment by dod38fr** [comment] 2021-09-22 12:28
@rerdavies What version of libconfig-model-dpkg-perl are you using ?

**Comment by dod38fr** [comment] 2021-09-22 12:36
@rerdavies and which debian package ? So  I can reproduce this bug.

**Comment by dod38fr** [comment] 2021-09-22 16:06
Adding a cache to licensecheck requires launching this command for each scanned file. The performance is disappointing. So the cache cannot be implemented in `cme`

**Comment by dod38fr** [comment] 2021-10-06 09:16
A fix for a crash related to `and/or` was released with libconfig-model-dpkg-perl 2.152.

**Closed by dod38fr** 2021-10-06 09:16 UTC
